# Generated by Django 3.2.9 on 2021-11-05 14:51

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='phone',
            field=models.CharField(max_length=13, validators=[users.validators.TelephoneNumberValidator()], verbose_name='Номер телефона'),
        ),
    ]
